services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmate-api
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - redis
    ports:
      - "${APP_PORT}:8000"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - taskmate-network

  db:
    image: postgres:13
    container_name: taskmate-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - taskmate-network

  redis:
    image: redis:alpine
    container_name: taskmate-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - taskmate-network

networks:
  taskmate-network:

volumes:
  pgdata:

